# Install taps
tap homebrew/completions
tap homebrew/dupes
tap homebrew/versions
tap jingweno/gh
tap josegonzalez/php
tap thoughtbot/formulae

# brew list -1
install ant
install apple-gcc42
install atk
install autoconf
install automake
install awscli
install bash-completion
install bdw-gc
install bison
install box
install brew-cask
install cairo
install cdrdao
install composer
install cmake
install coreutils
install cscope
install ctags
install curl-ca-bundle
install direnv
install docker
install docker-completion
install drush
install etcd
install etcdctl
install eye-d3
install fig
install flac
install fleetctl
install figlet
install fontconfig
install freetype
install gdbm
install gdk-pixbuf
install gettext
install gh
install git
install gitsh
install glib
install gnu-sed
install gnupg
install gobject-introspection
install graphviz
install gsl
install gtk+
install gtksourceview
install harfbuzz
install htop-osx
install hub
install icu4c
install imagesnap
install intltool
install jpeg
install jq
install jsonpp
install lame
install lcov
install less
install lesspipe
install libevent
install libffi
install libgit2
install libgpg-error
install libksba
install libmtp
install libpng
install libtiff
install libtool
install libusb
install libusb-compat
install libyaml
install linklint
install links
install lua
install luarocks
install macvim
install markdown
install mcrypt
install md5sha1sum
install meld
install mhash
install mongodb
install multitail
install mysql
install neovim
install newt
install node
install openssl
install pandoc
install pango
install phantomjs
install php-code-sniffer
install php56
install php56-intl
install php56-mcrypt
install php56-mongo
install php56-xdebug
install phplint
install phploc
install phpmd
install phpunit
install pixman
install pkg-config
install popt
install profanity
install py2cairo
install pygobject
install pygtk
install pygtksourceview
install python
install qcachegrind
install qt
install rarian
install readline
install reattach-to-user-namespace
install ruby
install s-lang
install s3cmd
install sox
install sqlite
install ssh-copy-id
install theharvester
install tidy
install tmux
install tmux-completion
install trash
install tree
install unar
install unixodbc
install urlview
install w3m
install wget
install xz
install z
install zlib
install zsh
install zsh-completions

#install profanity --with-terminal-notifier
#install --HEAD neovim

install ack
install vim --override-system-vi
tap homebrew/versions
update
doctor

bundle Brewfile-ruby
bundle ~/GitHub/dotfiles/

# Examples
#install bash
#install bash-completion
#install brew-cask
#install casperjs
#install cscope
#install curl
#install freetype
#install gdbm
#install gibo
#install git
#install git-extras
#install grep
#install heroku-toolbelt
#install imagemagick
#install jpeg
#install libevent
#install libpng
#install libtool
#install macvim
#install mongodb
#install mongoose
#install node
#install pcre
#install phantomjs
#install pkg-config
#install readline
#install redis
#install scons
#install sqlite
#install ssh-copy-id
#install tmux
#install tree
#install wget
#install xz
#install zsh

# brew list - MPB 3/22/14
#install autoconf
#install automake
#install bdw-gc
#install brew-cask
#install cdrdao
#install cscope
#install emacs
#install eye-d3
#install flac
#install fontconfig
#install freetype
#install gdbm
#install gettext
#install gh
#install git
#install gnupg
#install htop-osx
#install hub
#install icu4c
#install jpeg
#install jq
#install jsonpp
#install lame
#install less
#install lesspipe
#install libao
#install libevent
#install libogg
#install libpng
#install libtool
#install libvorbis
#install libyaml
#install links
#install macvim
#install mad
#install markdown
#install mcrypt
#install mongodb
#install mplayer
#install mplayershell
#install node
#install openssl
#install pcre
#install phantomjs
#install php55
#install php55-intl
#install php55-mcrypt
#install php55-mongo
#install php55-yaml
#install pkg-config
#install python
#install rbenv
#install readline
#install reattach-to-user-namespace
#install ruby-build
#install sox
#install sqlite
#install ssh-copy-id
#install tmux
#install trash
#install tree
#install unixodbc
#install urlview
#install w3m
#install wget
#install xz
#install yasm
#install zlib
#install zsh

#install ant
#install apple-gcc42
#install bash-completion
#install coreutils
#install ctags
#install figlet
#install git
#install gnu-sed
#install gnupg
#install graphviz
#install gsl
#install htop-osx
#install hub
#install imagesnap
#install jq
#install libgit2
#install links
#install macvim
#install mcrypt
#install meld
#install mongodb
#install multitail
#install mysql
#install newt
#install node
#install phantomjs
#install php-code-sniffer
#install php55-intl
#install php55-mongo
#install phplint
#install phploc
#install phpmd
#install phpunit
#install python
#install qcachegrind
#install reattach-to-user-namespace
#install ruby
#install s3cmd
#install ssh-copy-id
#install tmux
#install trash
#install tree
#install urlview
#install w3m
#install wget
#install zlib
#install zsh-completions

