# brew list -1
install atk
install autoconf
install automake
install bdw-gc
install cairo
install cmake
install cscope
install fontconfig
install freetype
install gdbm
install gdk-pixbuf
install gettext
install gh
install gitsh
install glib
install gobject-introspection
install gtk+
install gtksourceview
install harfbuzz
install icu4c
install intltool
install jpeg
install lame
install libevent
install libffi
install libpng
install libtiff
install libtool
install libyaml
install openssl
install pango
install php55
install pixman
install pkg-config
install popt
install py2cairo
install pygobject
install pygtk
install pygtksourceview
install qt
install rarian
install readline
install s-lang
install sqlite
install unixodbc
install xz

install ack
install vim --override-system-vi
tap homebrew/versions
update
doctor

bundle Brewfile-ruby
bundle ~/GitHub/dotfiles/

# Examples
#install bash
#install bash-completion
#install brew-cask
#install casperjs
#install cscope
#install curl
#install freetype
#install gdbm
#install gibo
#install git
#install git-extras
#install grep
#install heroku-toolbelt
#install imagemagick
#install jpeg
#install libevent
#install libpng
#install libtool
#install macvim
#install mongodb
#install mongoose
#install node
#install pcre
#install phantomjs
#install pkg-config
#install readline
#install redis
#install scons
#install sqlite
#install ssh-copy-id
#install tmux
#install tree
#install wget
#install xz
#install zsh

# brew list - MPB 3/22/14
#install autoconf
#install automake
#install bdw-gc
#install brew-cask
#install cdrdao
#install cscope
#install emacs
#install eye-d3
#install flac
#install fontconfig
#install freetype
#install gdbm
#install gettext
#install gh
#install git
#install gnupg
#install htop-osx
#install hub
#install icu4c
#install jpeg
#install jq
#install jsonpp
#install lame
#install less
#install lesspipe
#install libao
#install libevent
#install libogg
#install libpng
#install libtool
#install libvorbis
#install libyaml
#install links
#install macvim
#install mad
#install markdown
#install mcrypt
#install mongodb
#install mplayer
#install mplayershell
#install node
#install openssl
#install pcre
#install phantomjs
#install php55
#install php55-intl
#install php55-mcrypt
#install php55-mongo
#install php55-yaml
#install pkg-config
#install python
#install rbenv
#install readline
#install reattach-to-user-namespace
#install ruby-build
#install sox
#install sqlite
#install ssh-copy-id
#install tmux
#install trash
#install tree
#install unixodbc
#install urlview
#install w3m
#install wget
#install xz
#install yasm
#install zlib
#install zsh

#install ant
#install apple-gcc42
#install bash-completion
#install coreutils
#install ctags
#install figlet
#install git
#install gnu-sed
#install gnupg
#install graphviz
#install gsl
#install htop-osx
#install hub
#install imagesnap
#install jq
#install libgit2
#install links
#install macvim
#install mcrypt
#install meld
#install mongodb
#install multitail
#install mysql
#install newt
#install node
#install phantomjs
#install php-code-sniffer
#install php55-intl
#install php55-mongo
#install phplint
#install phploc
#install phpmd
#install phpunit
#install python
#install qcachegrind
#install reattach-to-user-namespace
#install ruby
#install s3cmd
#install ssh-copy-id
#install tmux
#install trash
#install tree
#install urlview
#install w3m
#install wget
#install zlib
#install zsh-completions

