install ant
install apple-gcc42
install bash-completion
install coreutils
install ctags
install figlet
install git
install gnu-sed
install gnupg
install graphviz
install gsl
install htop-osx
install hub
install imagesnap
install jq
install libgit2
install links
install macvim
install mcrypt
install meld
install mongodb
install multitail
install mysql
install newt
install node
install phantomjs
install php-code-sniffer
install php55-intl
install php55-mongo
install phplint
install phploc
install phpmd
install phpunit
install python
install qcachegrind
install reattach-to-user-namespace
install ruby
install s3cmd
install ssh-copy-id
install tmux
install trash
install tree
install urlview
install w3m
install wget
install zlib
install zsh-completions

# brew list -1
install atk
install autoconf
install automake
install bdw-gc
install cairo
install cmake
install cscope
install fontconfig
install freetype
install gdbm
install gdk-pixbuf
install gettext
install gh
install gitsh
install glib
install gobject-introspection
install gtk+
install gtksourceview
install harfbuzz
install icu4c
install intltool
install jpeg
install lame
install libevent
install libffi
install libpng
install libtiff
install libtool
install libyaml
install openssl
install pango
install php55
install pixman
install pkg-config
install popt
install py2cairo
install pygobject
install pygtk
install pygtksourceview
install qt
install rarian
install readline
install s-lang
install sqlite
install unixodbc
install xz

install ack
install vim --override-system-vi
tap homebrew/versions
update
doctor

bundle Brewfile-ruby
bundle ~/GitHub/dotfiles/

# Examples
#install bash
#install bash-completion
#install brew-cask
#install casperjs
#install cscope
#install curl
#install freetype
#install gdbm
#install gibo
#install git
#install git-extras
#install grep
#install heroku-toolbelt
#install imagemagick
#install jpeg
#install libevent
#install libpng
#install libtool
#install macvim
#install mongodb
#install mongoose
#install node
#install pcre
#install phantomjs
#install pkg-config
#install readline
#install redis
#install scons
#install sqlite
#install ssh-copy-id
#install tmux
#install tree
#install wget
#install xz
#install zsh
